site_name:        CutPruners.jl
repo_url:         https://github.com/JuliaPolyhedra/CutPruners.jl
site_description: Modular interface and implementation of cut pruning algorithms
site_author:      Benoît Legat and François Pacaud

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
